# Generated by Django 5.1.6 on 2025-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='childcell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentcell', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='menubaritems',
            name='parentcell',
        ),
        migrations.AddField(
            model_name='menubaritems',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
