# Generated by Django 5.1.6 on 2025-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_childcell_remove_menubaritems_parentcell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcell',
            name='name',
            field=models.TextField(default='', max_length=20),
        ),
    ]
